#!/bin/sh

set -e

case "$1" in
    configure)
        update-alternatives --install \
            /usr/bin/ctags ctags /usr/bin/ctags-universal 30
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
