#!/bin/sh

set -e

case "$1" in
    configure)
        update-alternatives \
	    --install /usr/bin/ctags ctags /usr/bin/ctags-universal 30 \
	    --slave /usr/share/man/man1/ctags.1.gz ctags.1.gz /usr/share/man/man1/ctags-universal.1.gz
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
